import os

class Config:
    GPT_API_KEY = os.getenv("GPT_API_KEY")
    MONGO_URI = os.getenv("MONGODB_URI")
    MONGO_DB = os.getenv("MONGODB_NAME")
    MONGO_COLLECTION_CLIENT = os.getenv("MONGO_COLLECTION_CLIENT")
    MONGO_COLLECTION_CLIMA = os.getenv("MONGO_COLLECTION_CLIMA")
    MONGO_COLLECTION_NOTICIAS = os.getenv("MONGO_COLLECTION_NOTICIAS")
    MONGO_COLLECTION_SEGUROS = os.getenv("MONGO_COLLECTION_SEGUROS")
